LU-4669 ldiskfs: do not export static inline functions
In ldiskfs/ldiskfs_extents.h, both ldiskfs_ext_store_pblock()
and ldiskfs_ext_pblock() are defined as static inline functions.
However, commit 49b06fba39e (http://review.whamcloud.com/4804)
exported these two functions in ldiskfs/extents.c, which is not
allowed by gcc and causes the following compile errors:

error: __ksymtab_ldiskfs_ext_pblock causes a section type conflict
error: __ksymtab_ldiskfs_ext_store_pblock causes a section type conflict

This patch fixes the above errors by not exporting the two functions.

This patch is back-ported from the following one:
Lustre-commit: e387b0e21c093ebbfb7571cd9e65a98d8e7e5718
Lustre-change: http://review.whamcloud.com/9401

Signed-off-by: Jian Yu <jian.yu@intel.com>
Change-Id: I9ba2aa39d9d9dc97e74bd29b8513b86eed7fe175
Reviewed-on: http://review.whamcloud.com/12431
Tested-by: Jenkins
Tested-by: Maloo <hpdd-maloo@intel.com>
Reviewed-by: John L. Hammond <john.hammond@intel.com>
Reviewed-by: Andreas Dilger <andreas.dilger@intel.com>