LU-20162 lprocfs: revert "LU-20162 obdclass: pin debugfs entries"
This reverts commit 095fa11ec026bc781f053af96026dfb53e2c5d0a.

This commit caused osd-zfs to fail to load:

osd_zfs: module uses symbols dsl_prop_register from proprietary module zfs, inheriting taint.
osd_zfs: Unknown symbol debugfs_file_get (err -2)
osd_zfs: Unknown symbol debugfs_file_put (err -2)
LustreError: Can't load module 'osd-zfs'

Signed-off-by: Timothy Day <timday@thelustrecollective.com>
Change-Id: I8c1c00a620194d60a7860eda4d8eb93dbe3c19bd
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/66554
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Yonatan Nachum <ynachum@amazon.com>
Reviewed-by: Andreas Dilger <adilger@thelustrecollective.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>