LU-18533 build: fix the common.postinst nonexistence issue
Since dkms v3.1.3, the common.postinst script was not installed
anymore with the install-redhat target, which caused the following
failure while installing lustre-client-dkms package:

  WARNING: /usr/lib/dkms/common.postinst does not exist.
  ERROR: DKMS version is too old and lustre-client was not
  built with legacy DKMS support.
  You must either rebuild lustre-client with legacy postinst
  support or upgrade DKMS to a more current version.

This patch fixes the above issue by using dkms add, build,
and install commands directly instead of the common.postinst script.

Test-Parameters: trivial
Test-Parameters: optional testgroup=full-dkms

Change-Id: If8a61e33d1ef37388e6de7836c00c3e425c2bdc0
Signed-off-by: Jian Yu <yujian@whamcloud.com>
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/57392
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Nathaniel Clark <nclark@whamcloud.com>
Reviewed-by: Li Xi <lixi@ddn.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Oleg Drokin <green@whamcloud.com>