LU-18925 build: 64k client do not use pgidx before defined
Build fix for 64k

dt_object.c:1034:53: error: 'pgidx' undeclared \
   (first use in this function); did you mean 'pid'?
 1034 |                 void *kaddr = kmap_local_page(pages[pgidx]);
      |                                                     ^~~~~
      |                                                     pid

Test-Parameters: trivial
Fixes: ea0bdfc7cf0 ("LU-18925 libcfs: prefer kmap_local_page")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I359b3a927b2360d327da6dd7d7a6b92c9f2281d5
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/60431
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Timothy Day <timday@amazon.com>
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Alexey Lyashkov <alexey.lyashkov@hpe.com>
Tested-by: Maloo <maloo@whamcloud.com>