LU-17525 tests: sanity/133a interop version checking
sanity/133a with 2.15.4 and master fails with:
   Error: 'The open counter on mds1 is 1, not 2'

Add a version check for at least 2.15.62 to exclude the extra
checks when the MDS does not have v2_15_61-63-g055f939979

Test-Parameters: testlist=sanity env=ONLY=133a clientarch=aarch64 clientdistro=el8.8
Test-Parameters: testlist=sanity env=ONLY=133a serverversion=2.15.4 serverdistro=el8.8
Test-Parameters: testlist=sanity env=ONLY=133a clientarch=aarch64 clientdistro=el8.8 serverversion=2.15.4 serverdistro=el8.8
Fixes: 055f939979 ("LU-17481 mdt: count all opens in mdt.*.md_stats")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: Ibb6eca7a5dcf295b419f7025a0167d70babe0f1f
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/54466
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Patrick Farrell <patrick.farrell@oracle.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>