*    socklnd:  fixed my stupid blunder that could cause the assertion      failure...
     LustreError: 20480:0:(socklnd_cb.c:788:ksocknal_launch_packet())
     ASSERTION(peer->ksnp_accepting > 0 ||
               ksocknal_find_connecting_route_locked(peer) != NULL) failed

*    iiblnd: fixed connection race and tested on boston, but didn't manage
     to exercise the race resolution code.