b=22589 llite_lib.c:234: undefined-reference to `__stack_chk_fail_local'
If liblustre.so is linked with -nostdlib it produces errors such as:
./llite_lib.o: In function `liblustre_process_log':
lustre/liblustre/llite_lib.c:234: undefined reference to `__stack_chk_fail_local'
on platforms where the stack-smashing protector is used (i.e. Ubuntu).

i=johann