LU-18130 build: make nodemap helpers functions static
Resolve build error:
.../nodemap_handler.c:570:5: error: no previous prototype \
  for 'nodemap_add_idmap_range' [-Werror=missing-prototypes]

Test-Parameters: trivial
Fixes: 8445f7b92f ("LU-17922 utils: added idmap range functionality")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I25cf93870b15df55fbddd4c58de7c65688662552
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/55992
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: jsimmons <jsimmons@infradead.org>
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
Reviewed-by: Jian Yu <yujian@whamcloud.com>
Reviewed-by: Maximilian Dilger <mdilger@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>