LU-19748 gni: build fixes for gni
libcfs/linux/linux-mem.h -> lustre_compat/linux/linux-mem.h
libcfs/linux/linux-misc.h -> lustre_compat/linux/linux-misc.h

__ll_vmalloc() -> __compat_vmalloc()

missing semi-colon after:
  ENUM2STR(GNI_RC_SUCCESS)

GNI needs to include:
  lustre_compat/linux/timer.h
  linux/libcfs/libcfs_fail.h

Build fix: -Werror=maybe-uninitialized

  .../lustre/mgc/mgc_request.c: In function 'mgc_create_new_conn':
  .../include/linux/libcfs/libcfs_debug.h:122:3: error: 'rc' may be
  used uninitialized in this function [-Werror=maybe-uninitialized]

      libcfs_debug_msg(&msgdata, format, ## __VA_ARGS__);
      ^~~~~~~~~~~~~~~~
  .../lustre/mgc/mgc_request.c:1208:6: note: 'rc' was declared here
     int rc;
         ^~

HPE-bug-id: LUS-13154
Test-Parameters: trivial
Fixes: a050dfb80dd5 ("LU-19229 mgc: client to handle IR with unknown nets")
Fixes: dbf4d41d9879 ("LU-18687 libcfs: move include to top-level)"
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I16dd895b2ba5a6322a0c629b083760ed930b659f
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/63216
Tested-by: Maloo <maloo@whamcloud.com>
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@thelustrecollective.com>
Reviewed-by: Mikhail Pershin <mpershin@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: Alexander Zarochentsev <alexander.zarochentsev@hpe.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>