LU-10391 socklnd: properly order headers in socklnd.h
We need the proper definitions in inetdevice.h for socklnd.h.
This breaks on newer platforms like Ubuntu18 with

error: implicit declaration of function ‘endfor_ifa’ [-Werror=implicit-function-declaration]

Reversing the order of the headers resolves this build issue.

Fixes: d720fbaada ("LU-10391 socklnd: use interface index to track local addr")
Change-Id: Id8fd27ca118c592b501b3d9241f87b05db3aba70
Signed-off-by: James Simmons <jsimmons@infradead.org>
Reviewed-on: https://review.whamcloud.com/38287
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Neil Brown <neilb@suse.de>
Reviewed-by: Serguei Smirnov <ssmirnov@whamcloud.com>
Reviewed-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>