LU-17259 lnet: kgnilnd_nl_get should return 0 on success
Fix build failure
error: control reaches end of non-void function [-Werror=return-type]

Test-Parameters: trivial
Fixes: d15bfca078 ("LU-10391 lnet: migrate full LNet NI information collection")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I09dd76c46620107d6c3f89cf59b9d9190578ef60
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/52972
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Petros Koutoupis <petros.koutoupis@hpe.com>
Reviewed-by: Chris Horn <chris.horn@hpe.com>
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>