LU-12511 utils: fix build issues with native client
A few bugs have crept in that breaks building the lustre utilies
against the native client. One set of breakage is the wrong
paths for UAPI lustre headers. A few server only data structures
have shown up so only conditionally build them. Lastly for
liblustreapi_ioctl.c we need stdlib.h so it builds properly.
Otherwise we get the build error:

liblustreapi_ioctl.c:63:11: error: incompatible implicit
		declaration of built-in function ‘malloc’ [-Werror]
liblustreapi_ioctl.c:63:11: note: include ‘<stdlib.h>’
			or provide a declaration of ‘malloc’

Test-Parameters: trivial
Change-Id: If942cef0fd810a918ef3953f7920021b5a5f8360
Signed-off-by: James Simmons <jsimmons@infradead.org>
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/58952
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Timothy Day <timday@amazon.com>
Reviewed-by: Arshad Hussain <arshad.hussain@aeoncomputing.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>