LU-20304 out: ignore quota errors for migration
When administrator runs file migration with sufficient privileges
(e.g. CAP_SYS_RESOURCE), migration could fail with -EDQUOT on the
local and remote MDT when the target user's inode quota is already
exhausted, even though the admin running the migration has the
necessary privileges. The quota check should be bypassed during
admin-initiated migration regardless of the target user's current
quota usage.

LustreError: 63678:0:(mdt_reint.c:2553:mdt_reint_migrate())
lustre-MDT0000: migrate [0x240000402:0x1:0x0]/f99 failed: rc = -122

Fix uses th_ignore_quota flag to bypass EDQUOT. And also adds
UPDATE_FL_IGNORE_QUOTA to propagate th_ignore_quota through
OUT rpc. To create a remote llog, let's use a zero UID/GID to
bypass the quota check.

test_300 is added to check the LFS migration with an inode quota
near the limit. Usually, migration is done by an administrator and
should skip quota checks.

HPE-bug-id: LUS-13370
Signed-off-by: Alexander Boyko <alexander.boyko@hpe.com>
Change-Id: Ie51f6cce73dd63617e4a1279a060aaadfa55e8fb
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/66150
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Alexander Zarochentsev <alexander.zarochentsev@hpe.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@thelustrecollective.com>