Revert "LU-19750 mdt: update mdt_changelog_allow() version check"
This reverts commit 1c0d9f16e4736f3ae0d907431bfdb290a24ac1e4.

The patch introduces a 100% crash is sanity-sec 35:

LustreError: 6513:0:(tgt_handler.c:464:tgt_handle_request0()) @@@ lustre-MDT0000: LLOG_ORIGIN_HANDLE_CREATE handler did not pack reply but returned no error  req@ffff89f74e518700 x1856272178213504/t0(0) o501->612038e1-324b-462d-af3f-0f82da51a39d@192.168.203.6@tcp:214/0 lens 520/0 e 0 to 0 dl 1770281934 ref 1 fl Interpret:/200/ffffffff rc 0/-1 job:'chlg_load_threa.0' uid:0 gid:0 projid:4294967295
[ 2940.465974] LustreError: 6513:0:(tgt_handler.c:465:tgt_handle_request0()) LBUG

Change-Id: Ie6f6fed8f52b633001f92f453ebc1c20a1339d13
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/63823
Tested-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>