LU-20417 build: ext-o2ib needs 'include/uapi' include path
Resolve build failure:

lustre-release/include/uapi/linux/lnet/lnet-types.h:21:10: \
fatal error: linux/lnet/lnet-idl.h: No such file or directory
   21 | #include <linux/lnet/lnet-idl.h>

Test-Parameters: trivial
Fixes: 4ff30bece1 ("LU-18687 build: refactor the top-level Makefile")
Signed-off-by: Shaun Tancheff <thornsarcana@gmail.com>
Change-Id: I75fd3bfe0bb6116cf4e1e2aa528399d06909c0cc
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/66798
Reviewed-by: Timothy Day <timday@thelustrecollective.com>
Tested-by: Maloo <maloo@whamcloud.com>
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Oleg Drokin <green@whamcloud.com>