LU-19570 build: unused 'ni' missing semi-colon
Fix missing semi-colon in gnilnd

lnet/klnds/gnilnd/gnilnd.c:37:18: error: \
   unused variable 'ni' [-Werror=unused-variable]

HPE-bug-id: LUS-13064, LUS-13095
Test-Parameters: trivial
Fixes: ea0bdfc7cf ("LU-18925 libcfs: prefer kmap_local_page")
Fixes: aa2fa25325 ("LU-10391 lnet: support setting LND timeouts")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I281ebafac054936547cdb25b90fe4790d8374a36
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/62331
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Reviewed-by: Nikitas Angelinas <nikitas.angelinas@hpe.com>
Reviewed-by: Chris Horn <chris.horn@hpe.com>
Tested-by: Maloo <maloo@whamcloud.com>
Tested-by: jenkins <devops@whamcloud.com>