b=17110 r=shadow,wangdi
- fixes wrong checking for obd_stopping in recov_thread which prevents recov_thread from sending llcds to
mds in disconnect time because obd_stopping is set before filter_disconnect() is called.

This causes issues like this:

LustreError: 6912:0:(filter.c:2446:filter_disconnect()) error flushing logs to MDS: rc -19