Revert "b=21485 Keep in-memory client data until export destroy"
This reverts commit 64d7c036a5429a9ce5435aea96e30935b1cef44a.

Causes compile error:
.../lustre/include/lu_target.h:59: error: 'LR_CLIENT_BITMAP_SIZE' undeclared here (not in a function)