LU-16518 ptlrpc: fix incompatible function type warnings
Fix errors of the type:

lustre/ptlrpc/layout.c:971:2: error: cast from
  'void (*)(struct mgs_target_info *)' to
  'void (*)(void *)' converts to incompatible
  function type [-Werror,-Wcast-function-type-strict]
  971 |         DEFINE_MSGF("mgs_target_info", 0, sizeof(struct mgs_target_info),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  972 |                     lustre_swab_mgs_target_info, NULL);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

by casting through 'void *', which breaks the incompatible
function-pointer cast the warning flags.

Test-Parameters: trivial
Signed-off-by: Timothy Day <timday@amazon.com>
Change-Id: I8418b0a1e6184c37e0eba9131121a1268edf300d
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/63241
Reviewed-by: Jinshan Xiong <jinshanx@google.com>
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: James Simmons <jsimmons@infradead.org>
Reviewed-by: Oleg Drokin <green@whamcloud.com>